name: py    
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest    
    steps:
      env:
        TARGET: vagrant
        TARGET: msvc2015-win64
        src-dir: https://github.com/ZawadzkiKonrad/wkhtml
      run: python build           