name: runner    
on: push
jobs:
  build:
    runs-on: windows-latest    
    steps:
      name: execute py script
      env:
        TARGET: vagrant
        TARGET: msvc2015-win64
        src-dir: '*/wkhtml'
      run: python build   